### ISSUE TITLE
Err GuildMemberAdd.js

### ISSUE THREAD

**Issue by thomasbnt** [thomasbnt/Bord-Pi#11]
Impossible de récupérer `member` ou `guild` dans le fichier et afficher dans la console et/ou en message>guild un retour. 

Lien du fichier https://github.com/thomasbnt/Bord-Pi/blob/handler/events/guildMemberAdd.js

**Comment by LucasCtrl** [comment]
Change le fichier par ceci et ça sera reparti 😉 
```js
module.exports = (bot, member) => {
    console.log(member.user.username + " join the server")
}
```

**Comment by thomasbnt** [comment]
C'est bien cette err que j'avais la dernière fois en faisant la même chose.

```bash
(node:22211) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'username' of undefined
    at module.exports ([...]/Bord-Pi/events/guildMemberAdd.js:2:29)
    at emitOne (events.js:116:13)
```

**Comment by LucasCtrl** [comment]
Essaie de log member et regarde ce qu'il ce passe

**Comment by thomasbnt** [comment]
Après avoir loggé, il ressort bien ce qu'il devrait ressortir.

Code Final : 


```js
module.exports = (bot, WebhookPrivate, WebhookPublic, member) => {
    console.log(member.user.username)
}
```
